# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'REBO.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ReboDialog(object):
    def setupUi(self, ReboDialog):
        ReboDialog.setObjectName("ReboDialog")
        ReboDialog.resize(659, 508)
        self.ReboStack = QtWidgets.QStackedWidget(ReboDialog)
        self.ReboStack.setGeometry(QtCore.QRect(10, 10, 641, 491))
        self.ReboStack.setObjectName("ReboStack")
        self.homeScreen = QtWidgets.QWidget()
        self.homeScreen.setObjectName("homeScreen")
        self.BotTitle = QtWidgets.QLabel(self.homeScreen)
        self.BotTitle.setGeometry(QtCore.QRect(240, 10, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.BotTitle.setFont(font)
        self.BotTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.BotTitle.setWordWrap(True)
        self.BotTitle.setObjectName("BotTitle")
        self.formLayoutWidget = QtWidgets.QWidget(self.homeScreen)
        self.formLayoutWidget.setGeometry(QtCore.QRect(110, 150, 411, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.CustomerDetailsForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.CustomerDetailsForm.setContentsMargins(0, 0, 0, 0)
        self.CustomerDetailsForm.setObjectName("CustomerDetailsForm")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CustomerDetailsForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.CustomerDetailsForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.CustomerDetailsForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.contactLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.contactLineEdit.setObjectName("contactLineEdit")
        self.CustomerDetailsForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.contactLineEdit)
        self.emailIDLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.emailIDLabel.setFont(font)
        self.emailIDLabel.setObjectName("emailIDLabel")
        self.CustomerDetailsForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.emailIDLabel)
        self.emailLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.CustomerDetailsForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.emailLineEdit)
        self.companyNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.companyNameLabel.setFont(font)
        self.companyNameLabel.setObjectName("companyNameLabel")
        self.CustomerDetailsForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.companyNameLabel)
        self.companyNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.companyNameLineEdit.setObjectName("companyNameLineEdit")
        self.CustomerDetailsForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.companyNameLineEdit)
        self.clearPushButton = QtWidgets.QPushButton(self.homeScreen)
        self.clearPushButton.setGeometry(QtCore.QRect(150, 300, 75, 31))
        self.clearPushButton.setObjectName("clearPushButton")
        self.nextPushButton = QtWidgets.QPushButton(self.homeScreen)
        self.nextPushButton.setGeometry(QtCore.QRect(390, 300, 75, 31))
        self.nextPushButton.setObjectName("nextPushButton")
        self.ReboStack.addWidget(self.homeScreen)
        self.chatScreen = QtWidgets.QWidget()
        self.chatScreen.setObjectName("chatScreen")
        self.label_3 = QtWidgets.QLabel(self.chatScreen)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.audioPushButton = QtWidgets.QPushButton(self.chatScreen)
        self.audioPushButton.setGeometry(QtCore.QRect(270, 450, 75, 31))
        self.audioPushButton.setObjectName("audioPushButton")
        self.layoutWidget = QtWidgets.QWidget(self.chatScreen)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 611, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chatTextEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.chatTextEdit.setReadOnly(True)
        self.chatTextEdit.setObjectName("chatTextEdit")
        self.verticalLayout.addWidget(self.chatTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.horizontalLayout.addWidget(self.inputLineEdit)
        self.sendPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.sendPushButton.setObjectName("sendPushButton")
        self.horizontalLayout.addWidget(self.sendPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ReboStack.addWidget(self.chatScreen)
        self.elicitedRequirementsScreen = QtWidgets.QWidget()
        self.elicitedRequirementsScreen.setObjectName("elicitedRequirementsScreen")
        self.label_4 = QtWidgets.QLabel(self.elicitedRequirementsScreen)
        self.label_4.setGeometry(QtCore.QRect(250, 20, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.classificationPushButton = QtWidgets.QPushButton(self.elicitedRequirementsScreen)
        self.classificationPushButton.setGeometry(QtCore.QRect(280, 440, 75, 31))
        self.classificationPushButton.setObjectName("classificationPushButton")
        self.elicitedTextEdit = QtWidgets.QTextEdit(self.elicitedRequirementsScreen)
        self.elicitedTextEdit.setGeometry(QtCore.QRect(20, 60, 611, 371))
        self.elicitedTextEdit.setReadOnly(True)
        self.elicitedTextEdit.setObjectName("elicitedTextEdit")
        self.ReboStack.addWidget(self.elicitedRequirementsScreen)
        self.classifiedRequirementScreen = QtWidgets.QWidget()
        self.classifiedRequirementScreen.setObjectName("classifiedRequirementScreen")
        self.label_5 = QtWidgets.QLabel(self.classifiedRequirementScreen)
        self.label_5.setGeometry(QtCore.QRect(250, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.classifiedRequirementScreen)
        self.label_6.setGeometry(QtCore.QRect(40, 70, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.functionalRequirementTextEdit = QtWidgets.QTextEdit(self.classifiedRequirementScreen)
        self.functionalRequirementTextEdit.setGeometry(QtCore.QRect(40, 100, 561, 131))
        self.functionalRequirementTextEdit.setReadOnly(True)
        self.functionalRequirementTextEdit.setObjectName("functionalRequirementTextEdit")
        self.label_7 = QtWidgets.QLabel(self.classifiedRequirementScreen)
        self.label_7.setGeometry(QtCore.QRect(40, 240, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.nonFunctionalRequirementsTextEdit = QtWidgets.QTextEdit(self.classifiedRequirementScreen)
        self.nonFunctionalRequirementsTextEdit.setGeometry(QtCore.QRect(40, 270, 561, 131))
        self.nonFunctionalRequirementsTextEdit.setReadOnly(True)
        self.nonFunctionalRequirementsTextEdit.setObjectName("nonFunctionalRequirementsTextEdit")
        self.exitButton = QtWidgets.QPushButton(self.classifiedRequirementScreen)
        self.exitButton.setGeometry(QtCore.QRect(280, 410, 75, 31))
        self.exitButton.setObjectName("exitButton")
        self.ReboStack.addWidget(self.classifiedRequirementScreen)

        self.retranslateUi(ReboDialog)
        self.ReboStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ReboDialog)

    def retranslateUi(self, ReboDialog):
        _translate = QtCore.QCoreApplication.translate
        ReboDialog.setWindowTitle(_translate("ReboDialog", "ReBot"))
        self.BotTitle.setText(_translate("ReboDialog", "Smart Requirements Elicitation and Classification Bot"))
        self.label.setText(_translate("ReboDialog", "Name"))
        self.label_2.setText(_translate("ReboDialog", "Contact No."))
        self.emailIDLabel.setText(_translate("ReboDialog", "Email ID"))
        self.companyNameLabel.setText(_translate("ReboDialog", "Company Name"))
        self.clearPushButton.setText(_translate("ReboDialog", "Clear"))
        self.nextPushButton.setText(_translate("ReboDialog", "Next"))
        self.label_3.setText(_translate("ReboDialog", "REBO"))
        self.audioPushButton.setText(_translate("ReboDialog", "Audio"))
        self.inputLineEdit.setPlaceholderText(_translate("ReboDialog", "Enter your text here..."))
        self.sendPushButton.setText(_translate("ReboDialog", "Send"))
        self.label_4.setText(_translate("ReboDialog", "Elicited Requirements "))
        self.classificationPushButton.setText(_translate("ReboDialog", "Classify"))
        self.label_5.setText(_translate("ReboDialog", "Classified Requirements "))
        self.label_6.setText(_translate("ReboDialog", "Functional Requirements"))
        self.label_7.setText(_translate("ReboDialog", "Non Fuctional Requirements"))
        self.exitButton.setText(_translate("ReboDialog", "Exit"))

